-- MySQL Script generated by MySQL Workbench
-- Sun Dec 29 16:27:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema knihovnadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema knihovnadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knihovnadb` DEFAULT CHARACTER SET utf8 ;
USE `knihovnadb` ;

-- -----------------------------------------------------
-- Table `knihovnadb`.`stav`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`stav` (
  `idstav` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstav`),
  UNIQUE INDEX `idstav_UNIQUE` (`idstav` ASC) ,
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knihovnadb`.`titul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`titul` (
  `idtitul` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `stranky` INT UNSIGNED NOT NULL,
  `vydani` DATE NOT NULL,
  `fypocet` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtitul`),
  UNIQUE INDEX `idticket_UNIQUE` (`idtitul` ASC) ,
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knihovnadb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`role` (
  `idrole` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE INDEX `idrole_UNIQUE` (`idrole` ASC) ,
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knihovnadb`.`uzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`uzivatel` (
  `iduzivatel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `heslo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `idrole` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iduzivatel`, `idrole`),
  UNIQUE INDEX `iduzivatel_UNIQUE` (`iduzivatel` ASC) ,
  UNIQUE INDEX `heslo_UNIQUE` (`heslo` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC) ,
  INDEX `role1_idx` (`idrole` ASC) ,
  CONSTRAINT `role1`
    FOREIGN KEY (`idrole`)
    REFERENCES `knihovnadb`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knihovnadb`.`vypujcka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`vypujcka` (
  `idvyjpujcka` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vypujceni` DATE NOT NULL,
  `vraceni` DATE NOT NULL,
  `idstav` INT UNSIGNED NOT NULL,
  `iduzivatel` INT UNSIGNED NOT NULL,
  `idrole` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idvyjpujcka`, `idstav`, `iduzivatel`, `idrole`),
  UNIQUE INDEX `idkategorie_UNIQUE` (`idvyjpujcka` ASC) ,
  INDEX `stav_idx` (`idstav` ASC) ,
  INDEX `uzivatel1_idx` (`iduzivatel` ASC, `idrole` ASC) ,
  CONSTRAINT `stav`
    FOREIGN KEY (`idstav`)
    REFERENCES `knihovnadb`.`stav` (`idstav`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uzivatel1`
    FOREIGN KEY (`iduzivatel` , `idrole`)
    REFERENCES `knihovnadb`.`uzivatel` (`iduzivatel` , `idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knihovnadb`.`zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`zanr` (
  `idzanr` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idzanr`),
  UNIQUE INDEX `idoddeleni_UNIQUE` (`idzanr` ASC) ,
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knihovnadb`.`zanr_titul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`zanr_titul` (
  `idtitul` INT UNSIGNED NOT NULL,
  `idzanr` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtitul`, `idzanr`),
  INDEX `zanr1_idx` (`idzanr` ASC) ,
  INDEX `titul1_idx` (`idtitul` ASC) ,
  CONSTRAINT `titul1`
    FOREIGN KEY (`idtitul`)
    REFERENCES `knihovnadb`.`titul` (`idtitul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zanr1`
    FOREIGN KEY (`idzanr`)
    REFERENCES `knihovnadb`.`zanr` (`idzanr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `knihovnadb`.`vypujcka_titul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knihovnadb`.`vypujcka_titul` (
  `idtitul` INT UNSIGNED NOT NULL,
  `idvyjpujcka` INT UNSIGNED NOT NULL,
  `idstav` INT UNSIGNED NOT NULL,
  `iduzivatel` INT UNSIGNED NOT NULL,
  `idrole` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtitul`, `idvyjpujcka`, `idstav`, `iduzivatel`, `idrole`),
  INDEX `vypujcka1_idx` (`idvyjpujcka` ASC, `idstav` ASC, `iduzivatel` ASC, `idrole` ASC) ,
  INDEX `titul2_idx` (`idtitul` ASC) ,
  CONSTRAINT `titul2`
    FOREIGN KEY (`idtitul`)
    REFERENCES `knihovnadb`.`titul` (`idtitul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vypujcka1`
    FOREIGN KEY (`idvyjpujcka` , `idstav` , `iduzivatel` , `idrole`)
    REFERENCES `knihovnadb`.`vypujcka` (`idvyjpujcka` , `idstav` , `iduzivatel` , `idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
